-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "userschema"."user" add column "profileimage" text
--  null default 'image';
