-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE SEQUENCE userschema."leaves_leaveId_seq" AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
