-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE ONLY userschema.leaves ALTER COLUMN "leaveId" SET DEFAULT nextval('userschema."leaves_leaveId_seq"'::regclass);
