name: Deploy Hasura Endpoint

on:
  push:
    branches:
      - hasura-deploy-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          HASURA_ENDPOINT: https://next-gannet-85.hasura.app/v1/graphql
          HASURA_ADMIN_SECRET: Dc0ftxq7sXnG9DfbqABY4dSyHGPb1lRTgGOWlFlNq4C9zoLB5zK6tEmV28nCEog4
        run: |
          echo "HASURA_ENDPOINT=${HASURA_ENDPOINT}" >> $GITHUB_ENV
          echo "HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET}" >> $GITHUB_ENV

      - name: Apply Hasura migration
        run: |
          curl -X POST ${{ env.HASURA_ENDPOINT }} -H "Content-Type: application/json" -H "x-hasura-admin-secret: ${{ env.HASURA_ADMIN_SECRET }}" -d '{"type": "migrate", "args": {"database": "default"}}'

      - name: Apply Hasura metadata
        run: |
          curl -X POST ${{ env.HASURA_ENDPOINT }} -H "Content-Type: application/json" -H "x-hasura-admin-secret: ${{ env.HASURA_ADMIN_SECRET }}" -d '{"type": "metadata_apply", "args": {"allow_inconsistent_metadata": true}}'

      - name: Reload Hasura metadata
        run: |
          curl -X POST ${{ env.HASURA_ENDPOINT }} -H "Content-Type: application/json" -H "x-hasura-admin-secret: ${{ env.HASURA_ADMIN_SECRET }}" -d '{"type": "metadata_reload"}'
